/* eslint-disable */
/*
 * AUTO-GENERATED FILE.
 * Source: Docs/mekesh_resume.md
 * Generated by: scripts/extract-resume.mjs
 */

export const HOME_RESUME_DATA = {
  "sourceFile": "Docs/mekesh_resume.md",
  "generatedAt": "2026-04-06T15:48:39.589Z",
  "profile": {
    "name": "MEKESH KUMAR",
    "headline": "Final Year Undergraduate — Electrical & Electronics Engineering (Kongu Engineering College)",
    "objective": "Final-year Electrical and Electronics Engineering undergraduate seeking a Graduate Engineering Trainee (GET) position to apply strong fundamentals in embedded systems, industrial automation, and IoT-integrated hardware-software development. Equipped with hands-on project experience across real-time control systems, sensor interfacing, and intelligent monitoring platforms — backed by in-plant training in manufacturing environments. Eager to contribute to engineering excellence, learn from industry-led mentorship, and grow into a core technical role within a dynamic organisation.",
    "location": "Perundurai",
    "contact": {
      "phone": "+91 8220810170",
      "email": "mekesh.engineer@gmail.com",
      "linkedin": "linkedin.com/in/mekeshkumar",
      "github": "github.com/Mekesh-Engineer",
      "website": "freelancer.in/u/mekesh12"
    }
  },
  "education": [
    {
      "qualification": "B.E. – Electrical & Electronics Engineering",
      "institution": "Kongu Engineering College, Perundurai, Tamil Nadu",
      "year": "2023 – Present (Final Year)",
      "result": "CGPA: 7.71 (up to 5th Sem)"
    },
    {
      "qualification": "Higher Secondary Education (HSE)",
      "institution": "Govt. Boys Higher Secondary School, Palacode, Tamil Nadu",
      "year": "2021 – 2023",
      "result": "84%"
    },
    {
      "qualification": "SSLC",
      "institution": "DDCSM Matriculation School, Palacode, Tamil Nadu",
      "year": "2020 – 2021",
      "result": "84%"
    }
  ],
  "competencyDomains": [
    {
      "id": "electrical-electronics-fundamentals",
      "title": "Electrical & Electronics Fundamentals",
      "items": [
        "Circuit Design & Analysis",
        "Electrical Machines",
        "Power Systems",
        "Power Electronics",
        "EV & Motor Drivers",
        "Analog Electronics",
        "Digital Electronics",
        "Signals & Systems",
        "FPGA Design & Simulation",
        "Microprocessors & Microcontrollers",
        "Engineering Drawing",
        "Control Systems",
        "Power System Protection & Switchgear",
        "PCB Design Fundamentals",
        "Schematic Capture",
        "Electrical Wiring Diagrams",
        "Sensor Interfacing & Transducer Calibration",
        "Closed-Loop Control System Design"
      ]
    },
    {
      "id": "engineering-design-simulation-tools",
      "title": "Engineering Design & Simulation Tools",
      "items": [
        "Simulation",
        "MATLAB",
        "Simulink",
        "Proteus",
        "OrCAD PSpice",
        "Mi Power",
        "FPGA & Digital Design",
        "Xilinx Vivado",
        "Intel Quartus Prime",
        "CAD",
        "AutoCAD Electrical",
        "Autodesk Fusion 360"
      ]
    },
    {
      "id": "embedded-systems-industrial-automation",
      "title": "Embedded Systems & Industrial Automation",
      "items": [
        "Microcontroller Firmware",
        "ESP32",
        "Arduino Uno",
        "ARM-based Processors",
        "Embedded C/C++ Programming, Real-Time Control Logic, Peripheral Interfacing",
        "Servo Actuation",
        "Multi-Sensor Fusion",
        "FreeRTOS Concepts",
        "IoT Platform Integration",
        "Blynk IoT",
        "Wi-Fi-based Edge Systems",
        "OTA Updates"
      ]
    },
    {
      "id": "programming-software-skills",
      "title": "Programming & Software Skills",
      "items": [
        "Languages",
        "Python",
        "C",
        "Embedded C",
        "C++",
        "Java",
        "JavaScript",
        "Frontend",
        "React 19",
        "TypeScript",
        "Next.js",
        "React Native",
        "HTML5",
        "CSS3",
        "Tailwind CSS",
        "Bootstrap",
        "Build Tools: Vite",
        "Backend",
        "Express.js",
        "Flask",
        "WebSockets",
        "REST APIs",
        "Databases & Cloud",
        "Firebase"
      ]
    },
    {
      "id": "ai-machine-learning-skills",
      "title": "AI & Machine Learning Skills",
      "items": [
        "Core Technical Skills",
        "Programming: Python",
        "Frameworks & Libraries",
        "TensorFlow",
        "PyTorch",
        "Keras",
        "Scikit-learn",
        "Mathematics",
        "Linear Algebra",
        "Calculus",
        "Probability & Statistics",
        "Data Science: Pandas, NumPy, Matplotlib, Seaborn",
        "Data & Annotation",
        "Dataset Platforms",
        "Roboflow",
        "CVAT.ai",
        "Label Studio",
        "LabelMe",
        "Doccano",
        "Data Skills",
        "Dataset curation",
        "preprocessing",
        "augmentation",
        "SQL-based data management"
      ]
    }
  ],
  "projects": [
    {
      "id": "automated-rod-and-pipe-inspection-system",
      "title": "Automated Rod and Pipe Inspection System",
      "category": "Industrial Automation",
      "categoryTags": [
        "Industrial Automation",
        "Machine Vision"
      ],
      "techStack": [
        "Python",
        "OpenCV",
        "YOLOv8",
        "Flask",
        "ESP32-CAM",
        "C++"
      ],
      "summary": "An end-to-end automated quality inspection system replacing manual measurement with machine vision for manufacturing-line use.",
      "highlights": [
        "Programmed ESP32-CAM firmware in C++ to stream real-time JPEG frames over Wi-Fi via HTTP endpoints for low-latency video ingestion.",
        "Integrated computer vision algorithms (YOLOv8 + OpenCV) to detect surface defects and compute dimensional measurements with high accuracy.",
        "Built a multi-threaded Flask backend to handle concurrent video streams and serve inference results efficiently.",
        "Designed a live operator dashboard displaying FPS, inference latency, detection logs, and real-time video — replicating SCADA-like monitoring interfaces."
      ]
    },
    {
      "id": "v2x-communication-and-fleet-monitoring-system",
      "title": "V2X Communication and Fleet Monitoring System",
      "category": "Fleet Automation",
      "categoryTags": [
        "Fleet Automation",
        "Real-Time Telemetry"
      ],
      "techStack": [
        "Python",
        "Flask",
        "WebSockets",
        "SSE",
        "UDP",
        "ESP32",
        "C++"
      ],
      "summary": "A real-time vehicle-to-everything (V2X) telemetry and control platform for multi-device fleet coordination — analogous to industrial SCADA and remote monitoring systems.",
      "highlights": [
        "Architected a full-stack telemetry API ingesting high-frequency sensor data (distance, temperature, humidity, battery, IR obstacles) from distributed ESP32 edge nodes.",
        "Engineered a UDP auto-discovery service for zero-configuration dynamic IP resolution across local networks — applicable to industrial plant-floor device management.",
        "Built a thread-safe global state manager with mutex-protected command queuing to ensure reliable, non-blocking control instruction delivery.",
        "Implemented a low-latency MJPEG video proxy server to relay live ESP32-CAM feeds to a central dashboard, eliminating cross-origin network restrictions."
      ]
    },
    {
      "id": "smart-iot-based-event-and-venue-management-platform",
      "title": "Smart IoT-Based Event and Venue Management Platform",
      "category": "IoT Systems",
      "categoryTags": [
        "IoT Systems",
        "Full-Stack Engineering"
      ],
      "techStack": [
        "React 19",
        "TypeScript",
        "Firebase",
        "YOLOv8",
        "ESP32-CAM",
        "Python"
      ],
      "summary": "A full-stack IoT platform integrating hardware, cloud, and AI for real-time venue monitoring, automated access control, and crowd management.",
      "highlights": [
        "1st Prize – Tamizhanskills Ideathon 2026, New Prince Shri Bhavani College of Engineering, Chennai",
        "Deployed edge-based crowd density analysis (YOLOv8) to trigger autonomous safety alerts and gimbal control when occupancy thresholds were exceeded.",
        "Engineered a high-speed QR ticket validation system using ESP32-CAM with cryptographic security and automated gate actuation.",
        "Built a scalable serverless Firebase backend (Firestore + Cloud Functions) with multi-tier Role-Based Access Control (RBAC) and atomic ticket inventory synchronisation."
      ]
    },
    {
      "id": "iot-automated-waste-segregation-system",
      "title": "IoT Automated Waste Segregation System",
      "category": "Embedded Systems",
      "categoryTags": [
        "Embedded Systems",
        "Smart Automation"
      ],
      "techStack": [
        "C++",
        "ESP32",
        "Blynk IoT",
        "Inductive / Capacitive / IR Sensors",
        "Servo Motors"
      ],
      "summary": "An autonomous smart waste classification system demonstrating applied embedded control logic, multi-sensor fusion, and cloud-connected monitoring.",
      "highlights": [
        "Implemented multi-sensor fusion (inductive, capacitive, IR) for autonomous classification of metal, plastic, and organic waste.",
        "Programmed real-time embedded control logic to translate sensor readings into servo-driven sorting actuation — a direct analogy to PLC-controlled industrial sorting systems.",
        "Integrated Blynk IoT dashboard for remote monitoring of bin capacity, waste distribution, and system health via Wi-Fi."
      ]
    },
    {
      "id": "full-stack-portfolio-and-resume-builder-web-app",
      "title": "Full-Stack Portfolio and Resume Builder Web App",
      "category": "Full-Stack Web Engineering",
      "categoryTags": [
        "Full-Stack Web Engineering",
        "Product Systems"
      ],
      "techStack": [
        "React 19",
        "TypeScript",
        "Vite",
        "Firebase (Auth + Firestore)",
        "Framer Motion",
        "Zod",
        "Zustand",
        "Vitest"
      ],
      "summary": "A production-style full-stack web application for building, managing, and publishing technical portfolio and resume content with secure authentication, real-time data workflows, and modular UI architecture.",
      "highlights": [
        "Engineered a role-aware dashboard platform with protected routing, authentication callbacks, and centralised state management for profile, projects, resume, and settings modules.",
        "Built schema-validated content pipelines (Zod-based) for personal info, projects, experience, skills, themes, and contact forms to improve data integrity and reduce invalid submissions.",
        "Implemented real-time and productivity features including autosave hooks, clipboard/export utilities, analytics views, search/filter tooling, and responsive UI sections optimised for desktop and mobile.",
        "Structured the app into reusable component layers and feature modules, with test coverage using Vitest to support maintainability and iterative deployment."
      ]
    },
    {
      "id": "smart-hybrid-energy-management-system-using-fuzzy-logic",
      "title": "Smart Hybrid Energy Management System using Fuzzy Logic",
      "category": "Energy Systems",
      "categoryTags": [
        "Energy Systems",
        "Smart Grid Automation"
      ],
      "techStack": [
        "Arduino Mega",
        "Fuzzy Logic (eFLL)",
        "Proteus",
        "Embedded C",
        "ACS712 Current Sensors",
        "Power Electronics"
      ],
      "summary": "An intelligent energy optimisation system that dynamically manages load distribution between grid and renewable sources using fuzzy logic-based decision making.",
      "highlights": [
        "Designed a Fuzzy Logic Controller (FLC) using multi-parameter inputs (time, load, grid availability, battery status) to optimise energy usage decisions.",
        "Implemented real-time load monitoring using ACS712 current sensors and voltage divider circuits for battery state estimation.",
        "Built a relay-based switching architecture to dynamically route power between grid and battery for efficient energy utilisation.",
        "Simulated the complete system in Proteus Design Suite, including inverter, solar input, and load switching mechanisms."
      ]
    },
    {
      "id": "gps-based-smart-vehicle-horn-speed-regulation-system",
      "title": "GPS-Based Smart Vehicle Horn & Speed Regulation System",
      "category": "Embedded Systems",
      "categoryTags": [
        "Embedded Systems",
        "Intelligent Transportation"
      ],
      "techStack": [
        "ESP32",
        "GPS (NEO-6M)",
        "L298N Motor Driver",
        "Embedded C++",
        "Wi-Fi",
        "Web Server"
      ],
      "summary": "A geofence-aware smart vehicle system that automatically regulates speed and restricts horn usage in sensitive zones such as hospitals and campuses.",
      "highlights": [
        "Implemented GPS-based geofencing logic using the Haversine distance formula to detect zone entry in real time.",
        "Designed an adaptive motor control system using PWM to dynamically reduce vehicle speed inside restricted zones.",
        "Built a real-time web dashboard and control interface for telemetry monitoring and manual control (mobile and desktop).",
        "Integrated state-driven buzzer control logic to disable horn functionality and trigger alert feedback in restricted zones."
      ]
    },
    {
      "id": "cosmic-strikes-3d-arcade-space-shooter",
      "title": "Cosmic Strikes — 3D Arcade Space Shooter",
      "category": "Full-Stack Systems",
      "categoryTags": [
        "Full-Stack Systems",
        "Interactive 3D Applications"
      ],
      "techStack": [
        "React",
        "TypeScript",
        "Three.js",
        "React Three Fiber",
        "Node.js",
        "Express",
        "MongoDB / SQLite"
      ],
      "summary": "A high-performance full-stack 3D arcade shooter combining real-time rendering, game logic, and backend-driven leaderboards.",
      "highlights": [
        "Engineered a WebGL-based 3D rendering pipeline using React Three Fiber for smooth 60 FPS gameplay.",
        "Designed a scalable game architecture with Redux state management and modular component structure.",
        "Built a Node.js backend API with JWT authentication and leaderboard system supporting MongoDB and SQLite.",
        "Implemented dynamic gameplay systems including wave progression, difficulty scaling, and combo-based scoring logic."
      ]
    }
  ],
  "achievements": [
    {
      "year": "2026",
      "award": "1st Prize",
      "activity": "Smart IoT Event & Venue Management Platform",
      "event": "Tamizhanskills Ideathon 2026 — New Prince Shri Bhavani College of Engineering, Chennai"
    },
    {
      "year": "2025",
      "award": "3rd Prize",
      "activity": "ROV-Based Underwater Crack Detection System",
      "event": "Project Prism – Oracle 2025 — Government College of Technology, Coimbatore"
    },
    {
      "year": "2026",
      "award": "3rd Prize",
      "activity": "Smart IoT Event & Venue Management Platform",
      "event": "Elixir 2026 Technical Event — Government College of Engineering, Erode"
    },
    {
      "year": "2023",
      "award": "School First Rank",
      "activity": "Higher Secondary Examination",
      "event": "Govt. Boys Higher Secondary School, Palacode"
    }
  ],
  "training": {
    "inPlant": [
      {
        "organisation": "Hatsun Agro Products Ltd., Vellichandai",
        "duration": "15–19 July 2024",
        "description": "Gained hands-on exposure to industrial manufacturing operations, production line workflows, equipment maintenance practices, and plant automation systems."
      },
      {
        "organisation": "Pavithran Aseptic Fruit Products",
        "duration": "1–5 January 2025",
        "description": "Studied aseptic processing techniques, quality control protocols, instrumentation used in food-grade production, and compliance with industrial standards."
      }
    ],
    "visits": [
      {
        "location": "Radio Astronomy Centre (RAC), Ooty – November 2024",
        "context": "large-scale signal processing and RF systems"
      },
      {
        "location": "Kodaikanal Solar Observatory (KoSO) – March 2025",
        "context": "precision instrumentation and data acquisition systems"
      }
    ]
  },
  "certifications": [
    {
      "track": "Professional & Technical",
      "name": "Embedded Application Development using ARM Processors — Maven Silicon",
      "year": "2025"
    },
    {
      "track": "Professional & Technical",
      "name": "AutoCAD Electrical Design — Cadcentre Cochin",
      "year": "2023"
    },
    {
      "track": "Additional",
      "name": "Introduction to Generative AI — Google Cloud",
      "year": "2024"
    },
    {
      "track": "Additional",
      "name": "Java for Beginners — Infosys Springboard",
      "year": "2024"
    },
    {
      "track": "Additional",
      "name": "Energy Literacy Training — Energy Swaraj Foundation",
      "year": "2023"
    }
  ],
  "presentations": [
    {
      "title": "V2X Communication and Fleet Monitoring System",
      "events": [
        "Ideathon 2K24 (KEC)",
        "Robofiesta 2K25 (SREC)",
        "Autonix 2024 (KEC)",
        "Project Expo 2K25 (KEC)",
        "Proof of Concept 2K25 (KEC)"
      ]
    },
    {
      "title": "Smart IoT Event & Venue Management Platform",
      "events": [
        "Tech Aura 2026 – IEEE (KPR Institute)",
        "Elixir 2026 (GCE Erode)",
        "Exodia 2026 – ISTE Hackathon (KEC)",
        "Tech Fest 2K25 (KEC)",
        "Proof of Concept 2K25 (KEC)"
      ]
    },
    {
      "title": "ROV-Based Underwater Crack Detection System",
      "events": [
        "Oracle 2K25 — Government College of Technology, Coimbatore"
      ]
    }
  ],
  "memberships": [
    {
      "organisation": "ISTE – Indian Society for Technical Education",
      "role": "Executive Member (2024 – Present)",
      "description": "Actively contributed to organising technical events, workshops, and inter-departmental competitions at Kongu Engineering College."
    },
    {
      "organisation": "NSS – National Service Scheme",
      "role": "Executive Member (2024 – Present)",
      "description": "Led and participated in community outreach, rural development, and social responsibility programmes."
    }
  ],
  "languages": [
    "Tamil: Native",
    "English: Professional",
    "Hindi: Working"
  ],
  "interests": [
    "Embedded Systems & Firmware Development",
    "Industrial Automation & Control",
    "IoT & Smart Systems",
    "Power Electronics",
    "Computer Vision & AI-Integrated Engineering",
    "Full-Stack Industrial Software"
  ]
} as const;
